TestingSystem.Web/Controllers/GroupController.cs
using AspNetIdentity.Managers;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Education Unit Admin, Global Admin")]
    public class GroupController : Controller
    {
        private AdminDTO admin;
        private IEntityService<AdminDTO> adminService;
        private IEntityService<GroupDTO> groupService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<TeacherDTO> teacherService;
        private IEntityService<StudentDTO> studentService;
        private IEntityService<EducationUnitDTO> unitService;
        private IEntityService<SpecializationDTO> specService;
        private IEntityService<GroupsInTestDTO> groupInTestService;
        private IEntityService<TeachersInGroupDTO> teacherInGroupService;
        private IEntityService<TeachersInSubjectDTO> teacherInSubjectsService;

        private AdminDTO Admin
        {
            get
            {
                if (admin == null)
                    admin = adminService.FindBy(s => s.Email == User.Identity.Name).FirstOrDefault();
                return admin;
            }
        }

        public GroupController(IEntityService<GroupDTO> groupService,
                               IEntityService<AdminDTO> adminService,
                               IEntityService<StudentDTO> studentService,
                               IEntityService<SubjectDTO> subjectService,
                               IEntityService<TeacherDTO> teacherService,
                               IEntityService<EducationUnitDTO> unitService,
                               IEntityService<SpecializationDTO> specService,
                               IEntityService<GroupsInTestDTO> groupInTestService,
                               IEntityService<TeachersInGroupDTO> teacherInGroupService,
                               IEntityService<TeachersInSubjectDTO> teacherInSubjectsService)
        {
            this.specService = specService;
            this.unitService = unitService;
            this.adminService = adminService;
            this.groupService = groupService;
            this.teacherService = teacherService;
            this.subjectService = subjectService;
            this.studentService = studentService;
            this.groupInTestService = groupInTestService;
            this.teacherInGroupService = teacherInGroupService;
            this.teacherInSubjectsService = teacherInSubjectsService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> PartialIndex(string filter = null)
        {
            IEnumerable<GroupDTO> groups;
            if (this.Admin.IsGlobal)
                groups = await groupService.GetAllAsync();
            else
                groups = await groupService.FindByAsync(group => group.EducationUnitId == this.Admin.EducationUnitId);
            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(groups.Where(group => group.GroupName.ToLower().Contains(filter.ToLower())
                                                                        || group.SpecializationName.ToLower().Contains(filter.ToLower())
                                                                        || group.EducationUnitName.ToLower().Contains(filter.ToLower())));
            return PartialView(groups);
        }

        public async Task<ActionResult> Students(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null)
                return RedirectToAction("Index");
            var model = new GroupDetailsViewModel();
            model.Group = group;
            model.Students = await studentService.FindByAsync(student => student.GroupId == group.Id);
            return View(model);
        }

        public async Task<ActionResult> Tests(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null)
                return RedirectToAction("Index");
            var model = new GroupTestsViewModel();
            model.Group = group;
            foreach (var item in await groupInTestService.FindByAsync(git => git.GroupId == group.Id))
                model.Tests.Add(item);
            return View(model);
        }

        public async Task<ActionResult> Create()
        {
            if (this.Admin == null)
                return RedirectToAction("Index");
            var model = new CreateGroupViewModel();
            model.Group = new GroupDTO();
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName");
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName");
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Group.EducationUnitId = this.Admin.EducationUnitId ?? model.Group.EducationUnitId;
                model.Group = await groupService.AddOrUpdateAsync(model.Group);

                foreach (var id in model.SelectedTeachers)
                    teacherInGroupService.AddOrUpdate(new TeachersInGroupDTO() { TeacherInSubjectId = id, GroupId = model.Group.Id });
                return RedirectToAction("Index");
            }
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", model.Group.SpecializationId);
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName");
            return View(model);
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null || this.Admin == null || (group.EducationUnitId != (this.Admin.EducationUnitId ?? 0) && !this.Admin.IsGlobal))
                return RedirectToAction("Index");
            var model = new CreateGroupViewModel()
            {
                Group = group,
                Teachers = (await teacherInSubjectsService.FindByAsync(tis => tis.SpecializationId == group.SpecializationId && !tis.IsDeleted)).ToList(),
                SelectedTeachers = (await teacherInGroupService.FindByAsync(tig => tig.GroupId == group.Id)).Select(tig => tig.TeacherInSubjectId).ToList()
            };
            model.SelectTeacherItems = model.Teachers.Select(tis => new SelectListItem() { Value = tis.Id.ToString(), Text = tis.FirstName + " " + tis.LastName }).ToList();
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName", group.EducationUnitId);
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", group.SpecializationId);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                var oldTeachers = await teacherInGroupService.FindByAsync(tig => tig.GroupId == model.Group.Id);
                await teacherInGroupService.DeleteRangeAsync(oldTeachers);

                await groupService.AddOrUpdateAsync(model.Group);
                foreach (var teacher in model.SelectedTeachers)
                    await teacherInGroupService.AddOrUpdateAsync(new TeachersInGroupDTO { TeacherInSubjectId = teacher, GroupId = model.Group.Id });
                return RedirectToAction("Index");
            }
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", model.Group.SpecializationId);
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName", model.Group.EducationUnitId);
            return View(model);
        }

        public async Task<ActionResult> Cancel(int id = 0)
        {
            var item = await groupInTestService.GetAsync(id);
            if (item != null && this.Admin != null && (item.EducationUnitId == (this.Admin.EducationUnitId ?? 0) || this.Admin.IsGlobal))
            {
                await groupInTestService.DeleteAsync(item);
                return RedirectToAction("Tests", item.GroupId);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int id = 0)
        {
            var item = await groupService.GetAsync(id);
            if (item != null && this.Admin != null && (item.EducationUnitId == this.Admin.EducationUnitId || this.Admin.IsGlobal))
            {
                var users = await studentService.FindByAsync(user => user.GroupId == item.Id);
                if (users.Count() != 0)
                    return Json($"There are users relying on such group: Id = {item.Id}, GroupName = {item.GroupName}", JsonRequestBehavior.AllowGet);
                await groupService.DeleteAsync(item);

TestingSystem.Web/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    public class ServiceController : Controller
    {
        private IEntityService<GroupDTO> groupService;
        private IEntityService<TeacherDTO> teacherService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<EducationUnitDTO> unitService;
        private IEntityService<SubjectThemeDTO> themeService;
        private IEntityService<SpecializationDTO> specService;
        private IEntityService<QuestionAnswerDTO> answerService;
        private IEntityService<TeachersInSubjectDTO> teacherInSubjectService;

        public ServiceController(IEntityService<GroupDTO> groupService,
                                 IEntityService<TeacherDTO> teacherService,
                                 IEntityService<SubjectDTO> subjectService,
                                 IEntityService<SubjectThemeDTO> themeService,
                                 IEntityService<EducationUnitDTO> unitService,
                                 IEntityService<SpecializationDTO> specService,
                                 IEntityService<QuestionAnswerDTO> answerService,
                                 IEntityService<TeachersInSubjectDTO> teacherInSubjectService)
        {
            this.unitService = unitService;
            this.specService = specService;
            this.themeService = themeService;
            this.groupService = groupService;
            this.answerService = answerService;
            this.teacherService = teacherService;
            this.subjectService = subjectService;
            this.teacherInSubjectService = teacherInSubjectService;
        }

        public JsonResult GetSubjectsBySpecialization(int id = 0)
        {
            var spec = specService.Get(id);
            if (spec != null)
                return Json(subjectService.FindBy(subject => subject.SpecializationId == spec.Id).Select(subject => new { Id = subject.Id, SubjectName = subject.SubjectName }), JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubjectsBySpecializationForTest(int id = 0)
        {
            var spec = specService.Get(id);
            if (spec != null)
                return Json(subjectService.FindBy(subject => subject.SpecializationId == spec.Id).Where(subject => subject.Questions != 0).Select(subject => new { Id = subject.Id, SubjectName = subject.SubjectName }), JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetThemesBySubject(int id = 0)
        {
            var subject = subjectService.Get(id);
            if (subject != null)
                return Json(themeService.FindBy(theme => theme.SubjectId == subject.Id).Select(theme => new { Id = theme.Id, ThemeName = theme.ThemeName }), JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetThemesBySubjectForTest(int id = 0)
        {
            var subject = subjectService.Get(id);
            if (subject != null)
                return Json(themeService.FindBy(theme => theme.SubjectId == subject.Id && theme.Questions > 0).Select(theme => new { Id = theme.Id, ThemeName = theme.ThemeName, EasyCount = theme.EasyCount, MediumCount = theme.MediumCount, HardCount = theme.HardCount}), JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeachersBySpecialization(int id = 0)
        {
            var spec = specService.Get(id);
            if (spec != null)
            {
                var teachers = teacherService.FindBy(teacher => teacher.SpecializationId == spec.Id && !teacher.IsDeleted);
                if (teachers == null || teachers.Count() == 0)
                    return Json(string.Empty, JsonRequestBehavior.AllowGet);
                var teacherSubjects = new List<TeacherSubject>();
                foreach (var teacher in teachers)
                {
                    var teachersInSubjects = teacherInSubjectService.FindBy(tis => tis.TeacherId == teacher.Id);
                    var subjectIds = teachersInSubjects.Select(tis => tis.SubjectId);
                    var subjects = subjectService.FindBy(subject => subjectIds.Contains(subject.Id) && subject.SpecializationId == spec.Id);
                    foreach (var subject in subjects)
                        teacherSubjects.Add(new TeacherSubject() { Teacher = teacher, Subject = subject, TeacherInSubjectId = teachersInSubjects.FirstOrDefault(t => t.TeacherId == teacher.Id && t.SubjectId == subject.Id)?.Id ?? 0 });
                }
                return Json(teacherSubjects.Select(user => new { Id = user.TeacherInSubjectId, FullName = user.Teacher.FirstName + " " + user.Teacher.LastName, SubjectName = user.Subject.SubjectName, Email = user.Teacher.Email}), JsonRequestBehavior.AllowGet);
            }
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetGroupsByUnit(int id = 0)
        {
            var unit = unitService.Get(id);
            if (unit != null)
                return Json(groupService.FindBy(group => group.EducationUnitId == unit.Id).Select(group => new { Id = group.Id, GroupName = group.GroupName }), JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task DeleteAnswer(int id = 0)
        {
            var item = await answerService.GetAsync(id);
            if (item != null)
                await answerService.DeleteAsync(item);
        }
    }
}

TestingSystem.Web/Views/Group/Create.cshtml
@model TestingSystem.Web.Models.ViewModels.CreateGroupViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm("Create", "Group"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Group.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Group.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Group.SpecializationName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Group.SpecializationId, (SelectList)ViewBag.Specializations, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Group.SpecializationId, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Global Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Group.EducationUnitName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Group.EducationUnitId, (SelectList)ViewBag.EducationUnits, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Group.EducationUnitId, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        <div class="form-group" id="teacher-cont-master">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link" id="collapse-show" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Teachers
                            </button>
                        </h2>
                    </div>

                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <label><input type="checkbox" id="ch-all" /> All</label>
                            <hr />
                            <div id="teachers-container">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <br />
                <input type="submit" value="Submit" class="btn btn-success" id="btn_submit" onclick="submitLimit()" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $("#Group_EducationUnitId").val([]);
            $("#Group_SpecializationId").val([]);


            $("#Group_SpecializationId").change(function () {
                $(".collapse").addClass("show");
                subjects = $("#teachers-container");
                $("#ch-all").prop('checked', false);
                $.getJSON("@Url.Action("GetTeachersBySpecialization", "Service")", { id: $(this).val() }, function (response) {
                    subjects.empty();
                    $.each(response, function (index, item) {
                        html = `<div class="row">
                                    <div class="col-dm-5 col-sm-5">
                                        <div class="checkbox">
                                            <label>
                                                 <input type="checkbox"
                                                        name="SelectedTeachers"
                                                        data-id="${item.Id}"
                                                        value="${item.Id}"/> ${item.FullName}
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-3">
                                        <label>${item.SubjectName}</label>
                                    </div>
                                    <div class="col-md-4 col-sm-4">
                                        <label>${item.Email}</label>
                                    </div>
                                </div>`;
                        subjects.append(subjects.append(html));
                    });
                });
            });

            $("#ch-all").change(function () {
                $('input:checkbox').prop('checked', $(this).prop('checked'));
            });

            $("body").on("change", 'input[name="SelectedTeachers"]', function () {
                numberOfChecked = $('input[name="SelectedTeachers"]:checked').length;
                numberOfAll = $('input[name="SelectedTeachers"]').length;
                if (numberOfChecked == numberOfAll) {
                    $("#ch-all").prop('checked', true);
                }
                else {
                    $("#ch-all").prop('checked', false);
                }
            });

            $("#btn_submit").click(function (e) {
                numberOfChecked = $('input:checkbox:checked').length;
                if (numberOfChecked == 0) {
                    e.preventDefault();
                    alert("Select at least one teacher");
                    return;
                }
            });
        });

        function submitLimit() {
            var btn = document.getElementById('btn_submit')
            setTimeout(function () {
                btn.setAttribute('disabled', 'disabled');
            }, 1);

            setTimeout(function () {
                btn.removeAttribute('disabled');
            }, 10000);
        }
    </script>
}

TestingSystem.Web/Views/Group/Edit.cshtml
@model TestingSystem.Web.Models.ViewModels.CreateGroupViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Group"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Group.Id)
        @Html.HiddenFor(model => model.Group.EducationUnitId)
        <div class="form-group">
            @Html.LabelFor(model => model.Group.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Group.SpecializationName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Group.SpecializationId, (SelectList)ViewBag.Specializations, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Group.SpecializationId, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Global Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Group.EducationUnitName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Group.EducationUnitId, (SelectList)ViewBag.EducationUnits, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Group.EducationUnitId, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link" id="collapse-show" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Teachers
                            </button>
                        </h2>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <label><input type="checkbox" id="ch-all" /> All</label>
                            <hr />
                            <div id="teachers-container">
                                @for (int i = 0; i < Model.Teachers.Count; i++)
                                {
                                    <div class="row">
                                        <div class="col-dm-5 col-sm-5">
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox"
                                                           name="SelectedTeachers"
                                                           @if (Model.SelectedTeachers.Contains(int.Parse(Model.SelectTeacherItems[i].Value))) {<text>checked</text>}
                                                           value="@Model.SelectTeacherItems[i].Value" /> @Model.SelectTeacherItems[i].Text
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-3 col-sm-3">
                                            <label>@Model.Teachers[i].SubjectName</label>
                                        </div>
                                        <div class="col-md-4 col-sm-4">
                                            <label>@Model.Teachers[i].Email</label>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" id="btn_submit" onclick="submitLimit()" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function submitLimit() {
            var btn = document.getElementById('btn_submit')
            setTimeout(function () {
                btn.setAttribute('disabled', 'disabled');
            }, 1);

            setTimeout(function () {
                btn.removeAttribute('disabled');
            }, 5000);
        }

        $(function () {
            numberOfChecked = $('input[name="SelectedTeachers"]:checked').length;
            numberOfAll = $('input[name="SelectedTeachers"]').length;
            if (numberOfChecked == numberOfAll) {
                $("#ch-all").prop('checked', true);
            }
            else {
                $("#ch-all").prop('checked', false);
            }


           $("#Group_SpecializationId").change(function () {
                subjects = $("#teachers-container");
                $("#ch-all").prop('checked', false);
                $.getJSON("@Url.Action("GetTeachersBySpecialization", "Service")", { id: $(this).val() }, function (response) {
                    subjects.empty();
                    $.each(response, function (index, item) {
                        html = `<div class="row">
                                    <div class="col-dm-5 col-sm-5">
                                        <div class="checkbox">
                                            <label>
                                                 <input type="checkbox"
                                                        name="SelectedTeachers"
                                                        data-id="${item.Id}"
                                                        value="${item.Id}"/> ${item.FullName}
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-3">
                                        <label>${item.SubjectName}</label>
                                    </div>
                                    <div class="col-md-4 col-sm-4">
                                        <label>${item.Email}</label>
                                    </div>
                                </div>`;
                        subjects.append(subjects.append(html));
                    });
                });
            });

            $("#ch-all").change(function () {
                $('input:checkbox').prop('checked', $(this).prop('checked'));
            });

            $("body").on("change", 'input[name="SelectedTeachers"]', function () {
                numberOfChecked = $('input[name="SelectedTeachers"]:checked').length;
                numberOfAll = $('input[name="SelectedTeachers"]').length;
                if (numberOfChecked == numberOfAll) {
                    $("#ch-all").prop('checked', true);
                }
                else {
                    $("#ch-all").prop('checked', false);
                }
            });

            $("#btn_submit").click(function (e) {
                numberOfChecked = $('input:checkbox:checked').length;
                if (numberOfChecked == 0) {
                    e.preventDefault();
                    alert("Select at least one teacher");
                    return;
                }
            });
        });
    </script>
}