TestingSystem.Web/Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestingSystem.Web.Controllers
{
    public class EducationController : Controller
    {
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Employment()
        {
            return View();
        }

        public ActionResult Tests()
        {
            return View();
        }

        public ActionResult Reviews()
        {
            return View();
        }
    }
}

TestingSystem.Web/Controllers/RoleController.cs
using AspNetIdentity.Managers;
using AspNetIdentity.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestingSystem.BOL.Service;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Global Admin")]
    public class RoleController : Controller
    {
        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialIndex(string filter = null)
        {
            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(RoleManager.Roles.Where(role => role.Name.ToLower().Contains(filter.ToLower())));
            return PartialView(RoleManager.Roles);
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var model = await RoleManager.FindByIdAsync(id) ?? new AppRole();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AppRole role)
        {
            if (ModelState.IsValid)
            {
                AppRole exists = RoleManager.FindById(role.Id);

                IdentityResult result;

                if (exists == null)
                    result = await RoleManager.CreateAsync(role);
                else
                    result = await RoleManager.UpdateAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error);
            }
            return View(role);
        }

        public async Task<ActionResult> Delete(int id = 0)
        {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                if (role.Users.Count != 0)
                    return Json($"There are users relying os such role: Id = {role.Id}, Role = {role.Name}", JsonRequestBehavior.AllowGet);
                await RoleManager.DeleteAsync(role);
                return Json($"Successfully deleted: #{role.Id} - \"{role.Name}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item found by such id: {id}", JsonRequestBehavior.AllowGet);
        }
    }
}

TestingSystem.Web/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TestController : Controller
    {
        private TeacherDTO teacher;
        private IEntityService<TestDTO> testService;
        private IEntityService<GroupDTO> groupService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<TeacherDTO> teacherService;
        private IEntityService<QuestionDTO> questionService;
        private IEntityService<SubjectThemeDTO> themeService;
        private IEntityService<SpecializationDTO> specService;
        private IEntityService<QuestionAnswerDTO> answerService;
        private IEntityService<GroupsInTestDTO> groupsInTestService;
        private IEntityService<ThemesInTestDTO> themesInTestsService;
        private IEntityService<TeachersInGroupDTO> teachersInGroupsService;
        private IEntityService<TeachersInSubjectDTO> teachersInSubjectsService;

        private TeacherDTO Teacher
        {
            get
            {
                if (teacher == null)
                    teacher = teacherService.FindBy(s => s.Email == User.Identity.Name).FirstOrDefault();
                return teacher;
            }
        }

        public TestController(IEntityService<TestDTO> testService,
                              IEntityService<GroupDTO> groupService,
                              IEntityService<TeacherDTO> teacherService,
                              IEntityService<SubjectDTO> subjectService,
                              IEntityService<QuestionDTO> questionService,
                              IEntityService<SubjectThemeDTO> themeService,
                              IEntityService<SpecializationDTO> specService,
                              IEntityService<QuestionAnswerDTO> answerService,
                              IEntityService<GroupsInTestDTO> groupsInTestService,
                              IEntityService<ThemesInTestDTO> themesInTestsService,
                              IEntityService<TeachersInGroupDTO> teachersInGroupsService,
                              IEntityService<TeachersInSubjectDTO> teachersInSubjectsService)
        {
            this.testService = testService;
            this.specService = specService;
            this.groupService = groupService;
            this.themeService = themeService;
            this.answerService = answerService;
            this.teacherService = teacherService;
            this.subjectService = subjectService;
            this.questionService = questionService;
            this.groupsInTestService = groupsInTestService;
            this.themesInTestsService = themesInTestsService;
            this.teachersInGroupsService = teachersInGroupsService;
            this.teachersInSubjectsService = teachersInSubjectsService;
        }

        public ActionResult Index()
        {
            if (Teacher == null)
                return RedirectToRoute("TeacherContent");
            return View();
        }

        public async Task<PartialViewResult> PartialIndex(string filter = null)
        {
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            var model = (await testService.FindByAsync(test => test.TeacherId == this.Teacher.Id && ids.Contains(test.SubjectId) && !test.IsDeleted)).ToList();
            foreach (var test in model)
                test.Themes = (await themesInTestsService.FindByAsync(tit => tit.TestId == test.Id)).ToList();


            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(model.Where(test => test.TestName.ToLower().Contains(filter.ToLower())
                                                                      || test.SpecializationName.ToLower().Contains(filter.ToLower())));
            ViewBag.DeletedTests = await testService.FindByAsync(test => test.TeacherId == this.Teacher.Id && ids.Contains(test.SubjectId) && test.IsDeleted);
            return PartialView(model);
        }

        public async Task<ActionResult> Create()
        {
            var model = new CreateTestViewModel()
            {
                Test = new TestDTO() { TeacherId = this.Teacher.Id },
                SelectThemeItems = new List<SelectListItem>(),
            };
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId).ToList();
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id) && subject.Questions > 0), "Id", "SubjectName"); ;
            return View(model);
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var test = await testService.GetAsync(id);
            if (test == null || test.TeacherId != this.Teacher.Id)
                return RedirectToAction("Index");

            var model = new CreateTestViewModel()
            {
                Test = test,
                SelectedThemes = (await themesInTestsService.FindByAsync(tit => tit.TestId == test.Id)).Select(tit => tit.ThemeId),
                Themes = (await themeService.FindByAsync(theme => theme.TeacherId == this.Teacher.Id && theme.Questions > 0 && theme.SubjectId == test.SubjectId)).ToList(),
            };
            model.SelectThemeItems = model.Themes.Select(theme => new SelectListItem() { Text = theme.ThemeName, Value = theme.Id.ToString() }).ToList();

            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id) && subject.Questions > 0), "Id", "SubjectName");
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CreateTestViewModel model)
        {
            if (ModelState.IsValid)
            {
                var oldThemes = await themesInTestsService.FindByAsync(tit => tit.TestId == model.Test.Id);
                await themesInTestsService.DeleteRangeAsync(oldThemes);

                model.Test = await testService.AddOrUpdateAsync(model.Test);
                foreach (var theme in model.SelectedThemes)
                    await themesInTestsService.AddOrUpdateAsync(new ThemesInTestDTO { ThemeId = theme, TestId = model.Test.Id });
                return RedirectToAction("Index");
            }
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id)), "Id", "SubjectName");
            model.Test = await testService.GetAsync(model.Test.Id);
            model.SelectedThemes = (await themesInTestsService.FindByAsync(tit => tit.TestId == model.Test.Id)).Select(tit => tit.ThemeId);
            model.Themes = (await themeService.FindByAsync(theme => theme.TeacherId == this.Teacher.Id && theme.Questions > 0 && theme.SubjectId == model.Test.SubjectId)).ToList();
            model.SelectThemeItems = (await themeService.FindByAsync(theme => theme.TeacherId == this.Teacher.Id && theme.Questions > 0 && theme.SubjectId == model.Test.SubjectId)).Select(theme => new SelectListItem() { Text = theme.ThemeName, Value = theme.Id.ToString() }).ToList();
            return View(model);
        }

        public async Task<JsonResult> Restore(int id = 0)
        {
            var item = await testService.GetAsync(id);
            if (item != null)
            {
                item.IsDeleted = false;
                await testService.AddOrUpdateAsync(item);
                return Json($"Successfully restored item: #{item.Id} - \"{item.TestName}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item with such id: {id}", JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> Delete(int id = 0)
        {
            var item = await testService.GetAsync(id);
            if (item != null && item.TeacherId == this.Teacher.Id)
            {
                item.IsDeleted = true;
                await testService.AddOrUpdateAsync(item);
                return Json($"Successfully archived item: #{item.Id} - \"{item.TestName}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item with such id: {id}", JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> DeleteForever(int id = 0)
        {
            var item = await testService.GetAsync(id);
            if (item != null && item.TeacherId == this.Teacher.Id && item.IsDeleted)
            {
                await testService.DeleteAsync(item);
                return Json($"Successfully deleted item: #{item.Id} - \"{item.TestName}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item with such id: {id}", JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public async Task<ActionResult> QuickTestSetup()
        {
            var model = new QuickTestSetupViewModel()
            {
                Specializations = await specService.GetAllAsync(),
                Subjects = await subjectService.GetAllAsync()
            };
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> QuickTestSetup(QuickTestSetupViewModel model)
        {

TestingSystem.Web/Views/Education/Tests.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="~/Design/StartPages/assets/images/ieslogo-182x93.png" type="image/x-icon">
    <meta name="description" content="Tests">
    <title>Tests</title>
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/web/assets/mobirise-icons2/mobirise2.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/web/assets/mobirise-icons-bold/mobirise-icons-bold.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/web/assets/mobirise-icons/mobirise-icons.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/tether/tether.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/bootstrap/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/bootstrap/css/bootstrap-grid.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/bootstrap/css/bootstrap-reboot.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/dropdown/css/style.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/animatecss/animate.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/theme/css/style.css")">
    <link rel="stylesheet" href="@Url.Content("~/Design/StartPages/assets/mobirise/css/mbr-additional.css")" type="text/css">
</head>
<body>
    <section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-5">
        <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm bg-color transparent">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="menu-logo">
                <div class="navbar-brand">
                    <span class="navbar-logo">
                        <a href="@Url.Action("Tests","Education")#header10-8">
                            <img src="@Url.Content("~/Design/StartPages/assets/images/ieslogo-182x93.png")" alt="" title="" style="height: 3.8rem;">
                        </a>
                    </span>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-white display-4" href="http://testingsystemapplication.azurewebsites.net/">
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Home","Education")#header2-1"><span class="mbri-browse mbr-iconfont mbr-iconfont-btn"></span>Main</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Tests","Education")#header10-8"><span class="mbrib-code mbr-iconfont mbr-iconfont-btn"></span>Tests</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Home","Education")#header15-5"><span class="mbri-rocket mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Partnership&nbsp;</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Employment","Education")#header6-9"><span class="mbri-briefcase mbr-iconfont mbr-iconfont-btn"></span>Employment</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Home","Education")#counters2-6"><span class="mobi-mbri mobi-mbri-briefcase mbr-iconfont mbr-iconfont-btn"></span>&nbsp;About&nbsp;</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Home","Education")#footer2-5"><span class="mbrib-contact-form mbr-iconfont mbr-iconfont-btn"></span>Contacts</a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="@Url.Action("Reviews","Education")"><span class="mbrib-preview mbr-iconfont mbr-iconfont-btn"></span>Reviews</a></li>
                </ul>
                @if (User.IsInRole("Teacher"))
                {
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-sm btn-primary display-4" href="@Url.Action("Groups","TeacherContent")">
                            <span class="mbrib-login mbr-iconfont mbr-iconfont-btn"></span>
                            BACK TO DASHBOARD
                        </a>
                    </div>
                }
                else if (User.IsInRole("Student"))
                {
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-sm btn-primary display-4" href="@Url.Action("Group","StudentContent")">
                            <span class="mbrib-login mbr-iconfont mbr-iconfont-btn"></span>
                            BACK TO SYSTEM
                        </a>
                    </div>
                }
                else if (User.IsInRole("Education Unit Admin"))
                {
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-sm btn-primary display-4" href="@Url.Action("Index","Role")">
                            <span class="mbrib-login mbr-iconfont mbr-iconfont-btn"></span>
                            BACK TO DASHBOARD
                        </a>
                    </div>
                }
                else if (User.IsInRole("Global Admin"))
                {
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-sm btn-primary display-4" href="@Url.Action("Index","Role")">
                            <span class="mbrib-login mbr-iconfont mbr-iconfont-btn"></span>
                            BACK TO DASHBOARD
                        </a>
                    </div>
                }
                else
                {
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-sm btn-primary display-4" href="@Url.Action("Login","Account")">
                            <span class="mbrib-login mbr-iconfont mbr-iconfont-btn"></span>
                            Login
                        </a>
                    </div>
                }
            </div>
        </nav>
    </section>
    <section class="header10 cid-rAo44N3vd4 mbr-fullscreen mbr-parallax-background" id="header10-8">
        <div class="container">
            <div class="media-container-column mbr-white p-5 align-left col-lg-8 col-md-10">
                <h1 class="mbr-section-title mbr-bold pb-3 mbr-fonts-style display-1">
                    DEVELOPER TESTS
                </h1>
                <p class="mbr-text pb-3 mbr-fonts-style display-5">
                    Whether or not you are an independently registered student on IES resources, you can take a test for developers in different areas and find out your level and what you need to know for further work in the IT field.
                </p>
                <div class="mbr-section-btn"><a class="btn btn-md btn-primary display-4" href="@Url.Action("QuickTestSetup","Test")">START THE TEST</a></div>
            </div>
        </div>
        <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
            <a href="#next">
                <i class="mbri-down mbr-iconfont"></i>
            </a>
        </div>
    </section>
    <section class="mbr-section info2 cid-rAo5qBJQk0" id="info2-e">
        <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(35, 35, 35);">
        </div>
        <div class="container">
            <div class="row main justify-content-center">
                <div class="media-container-column col-12 col-lg-3 col-md-4">
                    <div class="mbr-section-btn align-left py-4"><a class="btn btn-primary display-4" href="@Url.Action("Employment","Education")">APPLY NOW</a></div>
                </div>
                <div class="media-container-column title col-12 col-lg-7 col-md-6">
                    <h2 class="align-right mbr-bold mbr-white pb-3 mbr-fonts-style display-2">We need you</h2>
                    <h3 class="mbr-section-subtitle align-right mbr-light mbr-white mbr-fonts-style display-5">Join the professional team of IES developers!</h3>
                </div>
            </div>
        </div>
    </section>
    <script src="@Url.Content("~/Design/StartPages/assets/web/assets/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/tether/tether.min.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/popper/popper.min.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/bootstrap/js/bootstrap.min.js")"></script>
    <script async src="@Url.Content("~/Design/StartPages/assets/smoothscroll/smooth-scroll.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/dropdown/js/nav-dropdown.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/dropdown/js/navbar-dropdown.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/viewportchecker/jquery.viewportchecker.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/parallax/jarallax.min.js")"></script>
    <script async src="@Url.Content("~/Design/StartPages/assets/touchswipe/jquery.touch-swipe.min.js")"></script>
    <script src="@Url.Content("~/Design/StartPages/assets/theme/js/script.js")"></script>
    <script type="text/javascript">
        $('a').click(function () {
            $(this).attr('disabled', 'disabled');
            setTimeout(enableButton, 5000);
            return true;
        });
        var enableButton = function () {
            $('a').removeAttr('disabled');
        }
    </script>
    <input name="animation" type="hidden">
    <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
</body>
</html>