TestingSystem.Web/Controllers/GroupController.cs
using AspNetIdentity.Managers;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Education Unit Admin, Global Admin")]
    public class GroupController : Controller
    {
        private AdminDTO admin;
        private IEntityService<AdminDTO> adminService;
        private IEntityService<GroupDTO> groupService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<TeacherDTO> teacherService;
        private IEntityService<StudentDTO> studentService;
        private IEntityService<EducationUnitDTO> unitService;
        private IEntityService<SpecializationDTO> specService;
        private IEntityService<GroupsInTestDTO> groupInTestService;
        private IEntityService<TeachersInGroupDTO> teacherInGroupService;
        private IEntityService<TeachersInSubjectDTO> teacherInSubjectsService;

        private AdminDTO Admin
        {
            get
            {
                if (admin == null)
                    admin = adminService.FindBy(s => s.Email == User.Identity.Name).FirstOrDefault();
                return admin;
            }
        }

        public GroupController(IEntityService<GroupDTO> groupService,
                               IEntityService<AdminDTO> adminService,
                               IEntityService<StudentDTO> studentService,
                               IEntityService<SubjectDTO> subjectService,
                               IEntityService<TeacherDTO> teacherService,
                               IEntityService<EducationUnitDTO> unitService,
                               IEntityService<SpecializationDTO> specService,
                               IEntityService<GroupsInTestDTO> groupInTestService,
                               IEntityService<TeachersInGroupDTO> teacherInGroupService,
                               IEntityService<TeachersInSubjectDTO> teacherInSubjectsService)
        {
            this.specService = specService;
            this.unitService = unitService;
            this.adminService = adminService;
            this.groupService = groupService;
            this.teacherService = teacherService;
            this.subjectService = subjectService;
            this.studentService = studentService;
            this.groupInTestService = groupInTestService;
            this.teacherInGroupService = teacherInGroupService;
            this.teacherInSubjectsService = teacherInSubjectsService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> PartialIndex(string filter = null)
        {
            IEnumerable<GroupDTO> groups;
            if (this.Admin.IsGlobal)
                groups = await groupService.GetAllAsync();
            else
                groups = await groupService.FindByAsync(group => group.EducationUnitId == this.Admin.EducationUnitId);
            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(groups.Where(group => group.GroupName.ToLower().Contains(filter.ToLower())
                                                                        || group.SpecializationName.ToLower().Contains(filter.ToLower())
                                                                        || group.EducationUnitName.ToLower().Contains(filter.ToLower())));
            return PartialView(groups);
        }

        public async Task<ActionResult> Students(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null)
                return RedirectToAction("Index");
            var model = new GroupDetailsViewModel();
            model.Group = group;
            model.Students = await studentService.FindByAsync(student => student.GroupId == group.Id);
            return View(model);
        }

        public async Task<ActionResult> Tests(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null)
                return RedirectToAction("Index");
            var model = new GroupTestsViewModel();
            model.Group = group;
            foreach (var item in await groupInTestService.FindByAsync(git => git.GroupId == group.Id))
                model.Tests.Add(item);
            return View(model);
        }

        public async Task<ActionResult> Create()
        {
            if (this.Admin == null)
                return RedirectToAction("Index");
            var model = new CreateGroupViewModel();
            model.Group = new GroupDTO();
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName");
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName");
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Group.EducationUnitId = this.Admin.EducationUnitId ?? model.Group.EducationUnitId;
                model.Group = await groupService.AddOrUpdateAsync(model.Group);

                foreach (var id in model.SelectedTeachers)
                    teacherInGroupService.AddOrUpdate(new TeachersInGroupDTO() { TeacherInSubjectId = id, GroupId = model.Group.Id });
                return RedirectToAction("Index");
            }
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", model.Group.SpecializationId);
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName");
            return View(model);
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var group = await groupService.GetAsync(id);
            if (group == null || this.Admin == null || (group.EducationUnitId != (this.Admin.EducationUnitId ?? 0) && !this.Admin.IsGlobal))
                return RedirectToAction("Index");
            var model = new CreateGroupViewModel()
            {
                Group = group,
                Teachers = (await teacherInSubjectsService.FindByAsync(tis => tis.SpecializationId == group.SpecializationId && !tis.IsDeleted)).ToList(),
                SelectedTeachers = (await teacherInGroupService.FindByAsync(tig => tig.GroupId == group.Id)).Select(tig => tig.TeacherInSubjectId).ToList()
            };
            model.SelectTeacherItems = model.Teachers.Select(tis => new SelectListItem() { Value = tis.Id.ToString(), Text = tis.FirstName + " " + tis.LastName }).ToList();
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName", group.EducationUnitId);
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", group.SpecializationId);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                var oldTeachers = await teacherInGroupService.FindByAsync(tig => tig.GroupId == model.Group.Id);
                await teacherInGroupService.DeleteRangeAsync(oldTeachers);

                await groupService.AddOrUpdateAsync(model.Group);
                foreach (var teacher in model.SelectedTeachers)
                    await teacherInGroupService.AddOrUpdateAsync(new TeachersInGroupDTO { TeacherInSubjectId = teacher, GroupId = model.Group.Id });
                return RedirectToAction("Index");
            }
            ViewBag.Specializations = new SelectList(await specService.GetAllAsync(), "Id", "SpecializationName", model.Group.SpecializationId);
            ViewBag.EducationUnits = new SelectList(this.Admin.IsGlobal ? await unitService.GetAllAsync() : await unitService.FindByAsync(unit => unit.Id == this.Admin.EducationUnitId), "Id", "EducationUnitName", model.Group.EducationUnitId);
            return View(model);
        }

        public async Task<ActionResult> Cancel(int id = 0)
        {
            var item = await groupInTestService.GetAsync(id);
            if (item != null && this.Admin != null && (item.EducationUnitId == (this.Admin.EducationUnitId ?? 0) || this.Admin.IsGlobal))
            {
                await groupInTestService.DeleteAsync(item);
                return RedirectToAction("Tests", item.GroupId);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int id = 0)
        {
            var item = await groupService.GetAsync(id);
            if (item != null && this.Admin != null && (item.EducationUnitId == this.Admin.EducationUnitId || this.Admin.IsGlobal))
            {
                var users = await studentService.FindByAsync(user => user.GroupId == item.Id);
                if (users.Count() != 0)
                    return Json($"There are users relying on such group: Id = {item.Id}, GroupName = {item.GroupName}", JsonRequestBehavior.AllowGet);
                await groupService.DeleteAsync(item);

TestingSystem.Web/Controllers/SpecializationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Education Unit Admin, Global Admin")]
    public class SpecializationController : Controller
    {
        private AdminDTO admin;
        private IEntityService<TestDTO> testService;
        private IEntityService<AdminDTO> adminService;
        private IEntityService<TeacherDTO> userService;
        private IEntityService<GroupDTO> groupsService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<SpecializationDTO> specService;

        private AdminDTO Admin
        {
            get
            {
                if (admin == null)
                    admin = adminService.FindBy(s => s.Email == User.Identity.Name).FirstOrDefault();
                return admin;
            }
        }

        public SpecializationController(IEntityService<TeacherDTO> userService,
                                        IEntityService<TestDTO> testService,
                                        IEntityService<AdminDTO> adminService,
                                        IEntityService<GroupDTO> groupsService,
                                        IEntityService<SubjectDTO> subjectService,
                                        IEntityService<SpecializationDTO> specService)
        {
            this.testService = testService;
            this.specService = specService;
            this.userService = userService;
            this.adminService = adminService;
            this.groupsService = groupsService;
            this.subjectService = subjectService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<PartialViewResult> PartialIndex(string filter = null)
        {
            ViewBag.IsGlobal = this.Admin?.IsGlobal ?? false;
            ViewBag.EducationUnitId = this.Admin?.EducationUnitId;
            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(await specService.FindByAsync(spec => spec.SpecializationName.ToLower().Contains(filter.ToLower())));
            return PartialView(await specService.GetAllAsync());
        }

        public ActionResult Create()
        {
            return View(viewName: "Edit", model: new SpecializationDTO());
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var model = await specService.GetAsync(id);
            if (this.Admin == null || model == null || ((model.EducationUnitId ?? 0) != (this.Admin.EducationUnitId ?? 0) && !this.Admin.IsGlobal))
                return RedirectToAction("Index");
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(SpecializationDTO spec)
        {
            if (ModelState.IsValid)
            {
                spec.EducationUnitId = this.Admin.EducationUnitId;
                await specService.AddOrUpdateAsync(spec);
                return RedirectToAction("Index");
            }
            return View(spec);
        }

        public async Task<ActionResult> Groups(int id = 0)
        {
            var spec = await specService.GetAsync(id);
            if (spec == null || this.Admin == null)
                return RedirectToAction("Index");
            var model = new SpecGroupsViewModel
            {
                Groups = await groupsService.FindByAsync(group => group.SpecializationId == spec.Id),
                Specialization = spec
            };
            return View(model);
        }

        public async Task<ActionResult> Subjects(int id = 0)
        {
            var spec = await specService.GetAsync(id);
            if (spec == null || this.Admin == null)
                return RedirectToAction("Index");
            var model = new SpecSubjectsViewModel
            {
                Subjects = await subjectService.FindByAsync(subject => subject.SpecializationId == spec.Id),
                Specialization = spec
            };
            return View(model);
        }

        public async Task<ActionResult> Delete(int id = 0)
        {
            var item = await specService.GetAsync(id);
            if (item != null && this.Admin != null && ((item.EducationUnitId ?? 0) == (this.Admin.EducationUnitId ?? 0) || this.Admin.IsGlobal))
            {
                var tests = await testService.FindByAsync(test => test.SpecializationId == item.Id);
                var groups = await groupsService.FindByAsync(group => group.SpecializationId == item.Id);
                var subjects = await subjectService.FindByAsync(subject => subject.SpecializationId == item.Id);
                if (groups.Count() != 0)
                    return Json($"There are groups relying on such specialization: Id = {item.Id}, SpecName = {item.SpecializationName}", JsonRequestBehavior.AllowGet);
                if (tests.Count() != 0)
                    return Json($"There are tests relying on such specialization: Id = {item.Id}, SpecName = {item.SpecializationName}", JsonRequestBehavior.AllowGet);
                if (subjects.Count() != 0)
                    return Json($"There are subjects relying on such specialization: Id = {item.Id}, SpecName = {item.SpecializationName}", JsonRequestBehavior.AllowGet);
                await specService.DeleteAsync(item);
                return Json($"Successfully deleted: #{item.Id} - \"{item.SpecializationName}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item found by such id: {id}", JsonRequestBehavior.AllowGet);
        }
    }
}

TestingSystem.Web/Views/Specialization/Edit.cshtml
@model TestingSystem.BOL.Model.SpecializationDTO
@{
    ViewBag.Title = "Edit";
    //if (User.IsInRole("Education Unit Admin"))
    //{
    //    Layout = "~/Views/Shared/_UnitAdminLayout.cshtml";
    //}
    //if (User.IsInRole("Global Admin"))
    //{
    //}
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Specialization"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SpecializationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecializationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecializationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestingSystem.Web/Views/Specialization/Groups.cshtml
@model TestingSystem.Web.Models.ViewModels.SpecGroupsViewModel

@{
    ViewBag.Title = "Groups";
    //if (User.IsInRole("Education Unit Admin"))
    //{
    //    Layout = "~/Views/Shared/_UnitAdminLayout.cshtml";
    //}
    //if (User.IsInRole("Global Admin"))
    //{
    //}
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}

<h2>Specialization @Model.Specialization.SpecializationName Groups</h2>
<hr />

<div id="partial-content">
</div>

<p>
    @Html.ActionLink("Edit specialization", "Edit", new { id = Model.Specialization.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("#partial-content").load("@Url.Action("PartialIndex", "Group", new { filter = Model.Specialization.SpecializationName})");

            $("body").on("click", ".btn-delete", function (e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Group")",
                    data: { id: $(this).attr("data-id") },
                    success: function (data) {
                        $("#partial-content").load("@Url.Action("PartialIndex", "Group")");
                        $("#div-info").empty();
                        $("#div-info").append(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert("An error occured while processing request");
                    }
                });
            });

            $("body").on("keypress", "#filter-input", function (e) {
                if (e.which == 13)
                    $("#partial-content").load("@Url.Action("PartialIndex", "Group")", { filter : $(this).val()});
            });
        });

    </script>
}

TestingSystem.Web/Views/Specialization/Index.cshtml

@{
    ViewBag.Title = "Specialization";
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}

<h2>Specializations</h2>
<input type="text" id="filter-input" class="form-control" />
<div id="partial-content">
</div>

@Scripts.Render("~/bundles/jquery")
@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("#partial-content").load("@Url.Action("PartialIndex", "Specialization")");

            $("body").on("click", ".btn-delete", function (e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Specialization")",
                    data: { id: $(this).attr("data-id") },
                    success: function (data) {
                        $("#partial-content").load("@Url.Action("PartialIndex", "Specialization")");
                        $.notify({
	                        message: data
                        },{
	                        type: 'success'
                        });
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $.notify({
	                        message: "An error occured while processing your request"
                        },{
	                        type: 'danger'
                        });
                    }
                });
            });

            $("body").on("keypress", "#filter-input", function (e) {
                if (e.which == 13)
                    $("#partial-content").load("@Url.Action("PartialIndex", "Specialization")", { filter : $(this).val()});
            });
        });

    </script>
}

TestingSystem.Web/Views/Specialization/PartialIndex.cshtml
@model IEnumerable<TestingSystem.BOL.Model.SpecializationDTO>
<br />
<p> @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })</p>
@if (Model.Count() != 0)
{
    <div class="row">
        <div class="col-md-12">
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th> @Html.DisplayNameFor(model => model.SpecializationName)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SpecializationName)
                                </td>
                                <td>
                                    @Html.ActionLink("Groups", "Groups", new { id = item.Id }, new { }) |
                                    @Html.ActionLink("Subjects", "Subjects", new { id = item.Id }, new { }) |
                                    @if ((ViewBag.IsGlobal && ViewBag.EducationUnitId == null)
                                        || (item.EducationUnitId == ViewBag.EducationUnitId))
                                    {
                                        <span>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { }) |
                                        </span>
                                        <span>
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn-delete", data_id = item.Id })
                                        </span>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
else
{
    <div class="alert alert-info">
        No specializations
    </div>
}

TestingSystem.Web/Views/Specialization/Subjects.cshtml
@model TestingSystem.Web.Models.ViewModels.SpecSubjectsViewModel

@{
    ViewBag.Title = "Users";
    //if (User.IsInRole("Education Unit Admin"))
    //{
    //    Layout = "~/Views/Shared/_UnitAdminLayout.cshtml";
    //}
    //if (User.IsInRole("Global Admin"))
    //{
    //}
    Layout = "~/Views/Shared/_GlobalAdminLayout.cshtml";
}

<h2>Specialization @Model.Specialization.SpecializationName Subjects</h2>
<hr />

<div id="partial-content">
</div>

<p>
    @Html.ActionLink("Edit specialization", "Edit", new { id = Model.Specialization.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("#partial-content").load("@Url.Action("PartialIndex", "Subject", new { filter = Model.Specialization.SpecializationName})");

            $("body").on("click", ".btn-delete", function (e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Subject")",
                    data: { id: $(this).attr("data-id") },
                    success: function (data) {
                        $("#partial-content").load("@Url.Action("PartialIndex", "Subject")");
                        $("#div-info").empty();
                        $("#div-info").append(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert("An error occured while processing request");
                    }
                });
            });

            $("body").on("keypress", "#filter-input", function (e) {
                if (e.which == 13)
                    $("#partial-content").load("@Url.Action("PartialIndex", "Subject")", { filter : $(this).val()});
            });
        });

    </script>
}