TestingSystem.Web/Controllers/StudyingMaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using TestingSystem.BOL.Model;
using TestingSystem.BOL.Service;
using TestingSystem.Web.Models.ViewModels;

namespace TestingSystem.Web.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class StudyingMaterialController : Controller
    {
        private TeacherDTO teacher;
        private IEntityService<TeacherDTO> teacherService;
        private IEntityService<SubjectDTO> subjectService;
        private IEntityService<StudyingMaterialDTO> materialService;
        private IEntityService<TeachersInSubjectDTO> teachersInSubjectsService;

        private TeacherDTO Teacher
        {
            get
            {
                if (teacher == null)
                    teacher = teacherService.FindBy(s => s.Email == User.Identity.Name).FirstOrDefault();
                return teacher;
            }
        }

        public StudyingMaterialController(IEntityService<TeacherDTO> teacherService,
                                          IEntityService<SubjectDTO> subjectService,
                                          IEntityService<StudyingMaterialDTO> materialService,
                                          IEntityService<TeachersInSubjectDTO> teachersInSubjectsService)
        {
            this.teacherService = teacherService;
            this.subjectService = subjectService;
            this.materialService = materialService;
            this.teachersInSubjectsService = teachersInSubjectsService;
        }

        public ActionResult Index()
        {
            if (Teacher == null)
                return RedirectToRoute("TeacherContent");
            return View();
        }

        public async Task<PartialViewResult> PartialIndex(string filter = null)
        {
            var model = await materialService.FindByAsync(material => material.TeacherId == this.Teacher.Id);
            if (!String.IsNullOrWhiteSpace(filter))
                return PartialView(model.Where(test => test.StudyingMaterialName.ToLower().Contains(filter.ToLower())));
            return PartialView(model);
        }

        public async Task<ActionResult> Create()
        {
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id)), "Id", "SubjectName");
            return View("Edit", new StudyingMaterialDTO());
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var model = await materialService.GetAsync(id);
            if (model == null || model.TeacherId != this.Teacher.Id)
                return RedirectToAction("Index");
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id)), "Id", "SubjectName");
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(StudyingMaterialDTO model)
        {
            if (ModelState.IsValid)
            {
                model.TeacherId = this.Teacher.Id;
                await materialService.AddOrUpdateAsync(model);
                return RedirectToAction("Index");
            }
            var ids = (await teachersInSubjectsService.FindByAsync(tis => tis.TeacherId == this.Teacher.Id)).Select(tis => tis.SubjectId);
            ViewBag.Subjects = new SelectList(await subjectService.FindByAsync(subject => ids.Contains(subject.Id)), "Id", "SubjectName");
            return View(model);
        }

        public async Task<JsonResult> Delete(int id = 0)
        {
            var item = await materialService.GetAsync(id);
            if (item != null && item.TeacherId == this.Teacher.Id)
            {
                await materialService.DeleteAsync(item);
                return Json($"Successfully deleted item: #{item.Id} - \"{item.StudyingMaterialName}\"", JsonRequestBehavior.AllowGet);
            }
            return Json($"No item with such id: {id}", JsonRequestBehavior.AllowGet);
        }
    }
}

TestingSystem.Web/Views/StudyingMaterial/Edit.cshtml
@model TestingSystem.BOL.Model.StudyingMaterialDTO
@{ ViewBag.Title = "Edit"; Layout = "~/Views/Shared/_TeacherLayout.cshtml"; }
@using (Html.BeginForm("Edit", "StudyingMaterial"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StudyingMaterialName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudyingMaterialName, new { htmlAttributes = new { @class = "form-control", id = "studyingName" } })
                @Html.ValidationMessageFor(model => model.StudyingMaterialName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubjectId, ViewBag.Subjects as SelectList, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control", id = "studyLink" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" id="submit" onclick="submitLimit()" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#submit").click(function () {
            if ($("#studyLink").val() == '' || $("#studyingName").val() == '') {
                alert('You must fill in all the required fields');
            }
        });
        function submitLimit() {
            var btn = document.getElementById('submit')
            setTimeout(function () {
                btn.setAttribute('disabled', 'disabled');
            }, 1);

            setTimeout(function () {
                btn.removeAttribute('disabled');
            }, 10000);
        }
    </script>
}

TestingSystem.Web/Views/StudyingMaterial/Index.cshtml
@{ ViewBag.Title = "Materials"; Layout = "~/Views/Shared/_TeacherLayout.cshtml"; }
<div style="background-color: white;">
    <h2>Materials</h2>
    <input type="text" id="filter-input" class="form-control" />
    <div id="partial-content">
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@section Scripts{
    <script src="@Url.Content("~/Scripts/bootstrap-notify.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            $("#partial-content").load("@Url.Action("PartialIndex", "StudyingMaterial")");
            $("body").on("click", ".btn-delete", function (e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "StudyingMaterial")",
                    data: { id: $(this).attr("data-id") },
                    success: function (data) {
                        $("#partial-content").load("@Url.Action("PartialIndex", "StudyingMaterial")");
                        $.notify({
	                        message: data
                        },{
	                        type: 'success'
                        });
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $.notify({
	                        message: "An error occured while processing your request"
                        },{
	                        type: 'danger'
                        });
                    }
                });
            });
            $("body").on("keypress", "#filter-input", function (e) {
                if (e.which == 13)
                    $("#partial-content").load("@Url.Action("PartialIndex", "StudyingMaterial")", { filter : $(this).val()});
            });
        });
    </script>
}

TestingSystem.Web/Views/StudyingMaterial/PartialIndex.cshtml
@model IEnumerable<TestingSystem.BOL.Model.StudyingMaterialDTO>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model.Count() != 0)
{
    <div class="row">
        <div class="col-md-12">
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.StudyingMaterialName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SubjectName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Link)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudyingMaterialName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SubjectName)
                                </td>
                                <td>
                                    <a href="@Html.DisplayFor(modelItem => item.Link)">Link to resource </a>
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn-delete", data_id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
else
{
    <div class="alert alert-info">
        No materials
    </div>
}